### ISSUE TITLE
php artisan make:filament-user Throws error

### ISSUE THREAD

**Issue by fullsendai** [rahulhaque/soketi-app-manager-filament#1]
Hi, when i run command, it throws error below:
Any suggestion why?

Laravel\Prompts\Exceptions\NonInteractiveValidationException 

  Required.

  at vendor/laravel/prompts/src/Concerns/Interactivity.php:32
     28▕ 
     29▕         $this->validate($default);
     30▕ 
     31▕         if ($this->state === 'error') {
  ➜  32▕             throw new NonInteractiveValidationException($this->error);
     33▕         }
     34▕ 
     35▕         return $default;
     36▕     }

      +17 vendor frames 

  18  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by rahulhaque** [comment]
@fullsendai I found no problem on fresh install following the instructions in the readme. Post your environment info and how to reproduce this error in step by step.

**Comment by fullsendai** [comment]
> @fullsendai I found no problem on fresh install following the instructions in the readme. Post your environment info and how to reproduce this error in step by step.

I followed your installation guide, just now did fresh installation, up until migration, its all good, but creating user command fails with the same exact errors i described above. My environment is laravel forge / ngnix / mysql

**Comment by rahulhaque** [comment]
@fullsendai thanks for the info. However, I have closed this issue because the create user command is not a part of my project rather it's from [filamentphp-create-user](https://filamentphp.com/docs/3.x/panels/installation#create-a-user).

**Comment by rahulhaque** [comment]
@fullsendai can you please try this way `php artisan make:filament-user --name <your_name> --email <your_email> --password <your_password>`? I think your shell has something to do with this.
