### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by chrisreedio** [rahulhaque/soketi-app-manager-filament#2]
I have this running locally using using PostgreSQL. 

I haven't really put it through it's paces yet but it appears everything is working fine out of the box.

I can report back after doing some more testing of sending events. I don't have webhook functionality planned but could look to add that as well just for testing purposes.

Just wanted to start a discussion on this as I was worried at first when I saw the requirements list MySQL.

**Comment by rahulhaque** [comment]
@chrisreedio thanks for trying it out. I have opened a discussion section. Please move this topic there after closing this. If you face no issue with PostgreSQL, I'll add that to the requirements list after you've done your tests. There's a way to add webhook in app edit page. Just not that interactive. Please confirm if you happen to try it out.
